name: my_messenger
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase SDK
  firebase_storage: ^11.7.7
  firebase_core: ^2.27.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.4

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Дополнительные пакеты
  cupertino_icons: ^1.0.8

  # Обновленная версия image_picker
  image_picker: ^1.0.7  # Последняя версия на 2025 год

  # Локализация
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # Библиотека для перевода строк

  # Шифрование сообщений
  encrypt: ^5.0.3  # AES-шифрование для безопасности

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Добавление assets (для аватаров и других ресурсов)
  assets:
    - assets/default_avatar.png